name: Build and Release JAR

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set short SHA
        id: vars
        run: echo "sha_short=$(echo $GITHUB_SHA | cut -c1-7)" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: commit-${{ steps.vars.outputs.sha_short }}
          name: "${{ steps.vars.outputs.sha_short }}"
          body: "Automated build for commit `${{ steps.vars.outputs.sha_short }}` on main"
          files: target/jellyfin-metacopy-1.0-SNAPSHOT-jar-with-dependencies.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
