name: Build and Release JAR

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          name: "Release for ${{ github.sha }}"
          body: "Automated build for commit `${{ github.sha }}` on main"
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
